spring.application.name=feed-service
server.port=8084

# Konekcija ka bazi na portu 5432 (mora kao i post-service)
spring.datasource.url=jdbc:postgresql://localhost:5432/feed_db
spring.datasource.username=postgres
spring.datasource.password=sifra

spring.jpa.hibernate.ddl-auto=update