# Pokreće unit testove na svaki kreirani/izmenjeni pull request
name: CI - Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit tests (all backend services)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # DAJE dozvolu za auth-service mvnw
      - name: Make auth-service mvnw executable
        run: chmod +x services/auth-service/mvnw

      - name: Run auth-service tests
        working-directory: services/auth-service
        run: ./mvnw test -B

      - name: Make root mvnw executable
        run: chmod +x mvnw

      - name: Run user-service tests
        working-directory: .
        run: ./mvnw test -B

      - name: Make post-service mvnw executable
        run: chmod +x post-service/mvnw

      - name: Run post-service tests
        working-directory: post-service
        run: ./mvnw test -B

      - name: Make interaction-service mvnw executable
        run: chmod +x interaction-service/mvnw

      - name: Run interaction-service tests
        working-directory: interaction-service
        run: ./mvnw test -B

      - name: Make feed-service mvnw executable
        run: chmod +x feed-service/mvnw

      - name: Run feed-service tests
        working-directory: feed-service
        run: ./mvnw test -B
